export const WEB_TITLE = 'AdMeta x Mina'
export const WEB_DESCRIPTION = 'AdMeta x Mina'

export const ADMETA_MSG_ACCOUNT = 'ADMETA_MSG_ACCOUNT'
export const ADMETA_MSG_SYNC_DATA = 'ADMETA_MSG_SYNC_DATA'
export const ADMETA_MSG_SYNC_DATA_BACK = 'ADMETA_MSG_SYNC_DATA_BACK'
export const ADMETA_MSG_UPDATE_SUCCESS = 'ADMETA_MSG_UPDATE_SUCCESS'

export const TEST_SIGN_ACCOUNT = 'EKF2DCTYXhScYF3vasvK275ErTNHMffvziFCwV9BsbfjPtRDGQ8V'

export const MIN_LEVEL = [50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 30000]