export const WEB_TITLE = 'AdMeta x Mina'
export const WEB_DESCRIPTION = 'AdMeta x Mina'

export const ADMETA_MSG_ACCOUNT = 'ADMETA_MSG_ACCOUNT'
export const ADMETA_MSG_SYNC_DATA = 'ADMETA_MSG_SYNC_DATA'
export const ADMETA_MSG_SYNC_DATA_BACK = 'ADMETA_MSG_SYNC_DATA_BACK'

export const TEST_SIGN_ACCOUNT = 'EKF2DCTYXhScYF3vasvK275ErTNHMffvziFCwV9BsbfjPtRDGQ8V'